### ISSUE TITLE
4K 10bit decoding bug in EncoderMode=12

### ISSUE THREAD

**Issue by luofalei** [intel/SVT-HEVC#124]
I tried to encode in the fastest mode for 4K 10bit sequence, like `Netflix_FoodMarket2`. There seems to have some bugs in the encoded bit-stream which made the `ffmpeg` decoder to output wrong images in the bottom rows in some frames.

The sequence could be downloaded from here:
https://media.xiph.org/video/derf/
And I used `ffmpeg` to convert it from `y4m` to `yuv420p10` format.

The decoding image and bit-stream is public here.
https://github.com/luofalei/svt-hevc-bug-info/tree/master/issue124

![decoding image sample][1]

  [1]: https://github.com/luofalei/svt-hevc-bug-info/raw/master/issue124/svt-hevc-encMode12-decoding-error.png

**Comment by luofalei** [comment]
The decoding image and bit-stream is public here.
https://github.com/luofalei/svt-hevc-bug-info/tree/master/issue124

![decoding image sample][1]

  [1]: https://github.com/luofalei/svt-hevc-bug-info/raw/master/issue124/svt-hevc-encMode12-decoding-error.png

**Comment by luofalei** [comment]
I tested the older versions and found it works good in 
```
SHA-1: 39574132c9b0cd83e5589fbb8da49d3a20e37973, Branch RevNo: 81

* Fix the frame rate issue (#108)

Signed-off-by: Jing Li <jing.b.li@intel.com>
```
However, the above decoding error appears in the later version such as
```
SHA-1: 51c5f427ad28320ec6765f9406ae02b25ca4c93d, Branch RevNo: 84

* Add 422/444 support (#105)

* Add 422/444 support in buf desc and PCS

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable 422/444 in ResourceCoordination Kernel

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable 422->420 chroma down sampling in MT kernel

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable denoise AVX optimization for 422/444

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable 422/444 in ModeDecision Kernel

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable 422/444 8/10bit support

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable 422/444 support at simple app

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Enable 422/444 at app level

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Add log info of color format

Signed-off-by: Jing Li <jing.b.li@intel.com>

* Clean up un-used parameters

Signed-off-by: Jing Li <jing.b.li@intel.com>
```

**Comment by tianjunwork** [comment]
@luofalei Thanks for the detailed reporting of the issue.

**Comment by kelvinhu325** [comment]
Hi Falei, I tired your test, but did not reproduce it, my generated bitstreams can be decoded correctly with and without this 51c5f427ad28320ec6765f9406ae02b25ca4c93d change, could you try to update to latest code and run it again? I fixed some bugs.
I also analyzed your bitstream with our internal tool, it shows several frames lack of slice end alignment zero bit, actually first error happens at second picture POC=8 (lcux=36, lcuy=31).
Error	19574	11	8	1957	CTB	alignment_bit_equal_to_zero shall be equal to 0.
Error	19573	11	8	1957	CTB	alignment_bit_equal_to_zero shall be equal to 0.
Error	19572	11	8	1957	CTB	alignment_bit_equal_to_zero shall be equal to 0.
Error	1399640	4	1	2175	CTB	Never saw end_of_slice_flag but reached end of picture
Error	1399640	4	1	2123	CTB	The value of MvdLX[x0][y0][compIdx] shall be in the range of -2^15 to 2^15-1, inclusive.

**Comment by kelvinhu325** [comment]
One more thing, you may try to run it with C code by setting "AsmType : 0" in enc.cfg file,  I doubt your machine may not support AVX512 assamble

**Comment by kelvinhu325** [comment]
attached my generated bitstream test.hevc for reference https://github.com/kelvinhu325/svt_bugs

**Comment by luofalei** [comment]
@kelvinhu325 I tested the latest version (`SHA-1: 4fdfae87fe0a97c56e99f5d4e505ddf69f02bcc6, Branch RevNo: 91`) but I doubt the bug still exists and changing `ASMType: 0` couldn't solve this problem. This bug appears ramdomly. In my test, the `PSNR` of the decoded video ranged from 12dB to 28dB.

My test enviroment is `Intel CPU i7-8700K`. The building solution was updated in my fork repo as follows.
https://github.com/luofalei/SVT-HEVC/tree/icc

And my testing script and log were put up here:
https://github.com/luofalei/svt-hevc-bug-info/tree/master/issue124/script

**Comment by kelvinhu325** [comment]
@luofalei your machine does not support AVX512, and should run with AVX2, I tried forcing AVX2 on my machine, it still work correctly, could you try below methods?
1, debug and see what's the value of function GetCpuAsmType() in your test? AsmType 3 means AVX512, 1 means AVX2
2, C test still has this issue may means compiler issue, what's your GCC version and OS? we run Ubuntu and GCC version is 5.4.0

**Comment by luofalei** [comment]
@kelvinhu325 Thanks for your effort in finding out the problem.

(1) `GetCpuAsmType()` returned `3` in my enviroment. It returned at here in `GetCpuAsmType()`.
```
    if (CanUseIntelCore4thGenFeatures() == 1){
        asmType = 3; // bit-field         // <== here
```
(2) I used `Intel C++ Compiler 19.0` under windows. 

I guess this problem was caused by variables which were not inited.

**Comment by HolyWu** [comment]
> 1, debug and see what's the value of function GetCpuAsmType() in your test? AsmType 3 means AVX512, 1 means AVX2

If I'm not mistaken, [here](https://github.com/intel/SVT-HEVC/blob/41d75656705aba587e4bf6b3e9496b73be51ab79/Source/Lib/Codec/EbEncHandle.c#L246) says that `7 for AVX512`, `3 for AVX2`, `1 for non-AVX2`. And `NON_AVX512_SUPPORT` is defined [here](https://github.com/intel/SVT-HEVC/blob/41d75656705aba587e4bf6b3e9496b73be51ab79/Source/Lib/Codec/EbDefinitions.h#L15) by default, hence users don't even get AVX512 code generated.

**Comment by kelvinhu325** [comment]
@luofalei @HolyWu , correcting my previous description, the first bit mistmatching happens at second picture POC=8 (lcux=53, lcuy=32), first recon yuv mismatching is at POC=8 (lcux=53, lcuy=31) bottom right two pixels, looks like deblocking output causes this error, could you try to disable deblocking by (LoopFilterDisable : 1) to see if it can work first?
since C test (asmType 0) can also reproduce this issue, assamble compiler may be not root cause, I tried to run this test on a SKL Centos machine, it works well, and I have no windows environment, so could not   help you debuging it on windows machine.

**Comment by luofalei** [comment]
@kelvinhu325 The decoding bug is caused by entropy coding I think.

Here is my revision for fixing this bug by changing the initial value and context derivation. 
https://github.com/luofalei/SVT-HEVC/commit/94576b0d8f8076fab55fabc410f01f22a6006958

Since this fix only takes `YUV420` format into account,  I didn't make a pull request.

**Comment by kelvinhu325** [comment]
@luofalei looks like the cbcbf2 and crcbf2 are not initialized on windows, this change is ok for YUV420, 422 and 444, while I notice you add some entropy part change in you another commit, what's that for?

**Comment by luofalei** [comment]
@kelvinhu325 I firstly revised these 2 lines in the entropy coding part by comparing the changes in the commit (51c5f427ad28320ec6765f9406ae02b25ca4c93d). This could solve some decoding error and the PSNR may improve, but bugs still exist. Later I found that this problem was caused by the `cbCbf2` and `crCbf2`. 

Only initialize `cbCbf2` and `crCbf2` could already solve this bug. And I see the pull request has been merged. I think this issue could be closed now.
